### PR TITLE
ADR-33: Cert Store

### PR DESCRIPTION
**Pull request by tbeets**
Design and enhancement to support certificate stores provided by operating systems or third-parties as NATS Server alternative to PEM file for client certificate and key.

### CODE REVIEW

**Comment by tbeets** [comment]
@derekcollison Ready to merge ADR-33, can you review?

**Comment by derekcollison** [comment]
For the design doc I think that is more Phil etc.. No?

**Comment by tbeets** [comment]
@philpennock Can you give a quick review?  Design same as briefed in November.  Added sections "Inclusion of Intermediate CA Certificates" and "Validation Policy".

**Comment by tbeets** [comment]
Will change the ADR number and re-submit PR.

**Pull request closed without merging**
