### PR TITLE
Add note about recreating ordered consumer

### PR DESCRIPTION
**Pull request by Jarema**
Ordered  Consumers should be recreated when heartbeats are missed.

This behaviour was not implemented in all clients and should be, especially after switching ordered consumers to memory storage and R1 which makes them much easier to loose.

This was found out in Go client in https://github.com/nats-io/nats.go/issues/1094

### CODE REVIEW

**Review by derekcollison — APPROVED** [review]
LGTM

**Comment by scottf** [comment]
I understand that mem_storage and num_replicas are optimizations, but are they needed for all ordered consumers or just KV? Are there cases (topology, etc.) where it's not appropriate to have these?
It also seems like we are making ordered consumer mean something else other than "just guarantee the order".
Maybe it's just a documentation issue? Maybe we should transition the name to something else like in the mode of simplification, make this a "managed" consumer?

**Comment by derekcollison** [comment]
For ordered consumers, we guarantee delivery in order and the way we achieve that today is that when an error condition is hit we create a new low level consumer picking up from the last good sequence we received, so these low level consumers should have a very light footprint in the system since we do not rely on their state after the client encounters an error.

**Review by aricart — APPROVED** [review]
LGTM

**Pull request merged**
